CREATE TABLE IF NOT EXISTS DBUSER(
    id       VARCHAR(255) PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255)        NOT NULL,
    salt     VARCHAR(255)        NOT NULL,
    role     ENUM('USER', 'ADMIN') DEFAULT 'USER'
);